GET http://localhost:3000/products 

### 
GET http://localhost:3000/products/:id

### Create Action
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "phone",
  "price": 1000,
  "img_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzUw4BRSv5KYO47illBY6pKjupBnnqXFEyluI3--QTAh3fU0whERswkeKRi2Bxw6817_Y&usqp=CAU",
  "description": "call and text; use internet services"
}

### Update Action
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  
  "price": "1250",
  "img_url": "beepboop",
  "description": "newer model"
}


### Delete Action
DELETE http://localhost:3000/products/3