@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgxNTkwMjR9.47SrDvE6UVJBA1z0RWnfoSEdIEGgkg8UyzXWo1srAwk



### products index
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}


### products show
GET http://localhost:3000/products/1.json

### products create
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Tulle Minidress",
  "price": 7200,
  "description": "A sparkling vocabulary, inspired by the language of eveningwear. This light tulle dress full of sophisticated details embodies the romantic spirit of Miu Miu. Its silhouette recalls the ballet world, while the edges are illuminated with precious details.",
  "supplier_id": 2
}

### products update
PATCH http://localhost:3000/products/1
Content-Type: application/json
Authorization: Bearer

{
  "name": "Medusa Aevitas Platform Pumps",
  "price": 1575,
  "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuzI8H95Jm68ujYk-A_8xkIIMMK9_oNX1i2w&usqp=CAU",
  "description": "A statement runway design, these satin pumps feature a high block heel and a double platform. The ankle strap is adorned with rhinestones and a signature Medusa charm."
}


### products delete
DELETE http://localhost:3000/products/2
Authorization: Bearer

### User Create 
POST http://localhost:3000/users 
Content-Type: application/json

{
  "name": "Daisy Z",
  "email": "daisy@test.com",
  "password": "password", 
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "daisy@test.com",
  "password": "password"
}

###Order create
POST  http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": "1",
  "quantity": "2",
}

### order show
GET http://localhost:3000/orders/1

### order index 
GET http://localhost:3000/orders.json


###Carted product create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 2,
  "quantity": 1, 
}

###Carted products index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
