GET http://localhost:3000/products.json

### Show Action
GET http://localhost:3000/products/1.json

### Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Fendi Multicolor Viscose Dress",
  "price": 1850,
  "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuzI8H95Jm68ujYk-A_8xkIIMMK9_oNX1i2w&usqp=CAU",
  "description": "Short close-fitting dress with high collar and long sleeves. Embellished with ribbed edges. Made of lightweight viscose knit with pastel-shades inlay.
The Stocking Girls graphics are a tribute to the visionary sensitivity of the fashion illustrator Antonio Lopez: recalling the atmospheres of the disco era and an expression of the free and universal femininity that distinguishes the Fendi spirit."
}

### Update Action
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Medusa Aevitas Platform Pumps",
  "price": 1575,
  "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuzI8H95Jm68ujYk-A_8xkIIMMK9_oNX1i2w&usqp=CAU",
  "description": "A statement runway design, these satin pumps feature a high block heel and a double platform. The ankle strap is adorned with rhinestones and a signature Medusa charm."
}


### Delete Action
DELETE http://localhost:3000/products/2